# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7502b51517b396ffb035ff1a309aeb203208b5a1d150dcfba14ac9674f797cc7c7b8402d872c58710d14e6e18a0ac3dd90f92fbd64a17de2f06eb1adaffb6612

test:
  secret_key_base: 2fefc2b7f9d0c63d1c584b01b16f1f3ffff3801f42030483727565a73b9f6214acd4e5ae358840bb1b8820c7aab1adf0cd39f4a5dc7328c5a52021554289fd17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
